# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a53a10ca478ab56893ed599e728365ddbe99114956cb0e36ee03f71eed29cde71303c0220818b1a9a40f2b1453d70f4281b8ff78fd9a9fa3fb2b88dfab02df78

test:
  secret_key_base: 7384dd6b71bb291ff58308df395283bbe00312a049d80f9aa8cce8caed8e81efbcf8d8232038cf54385fb69942bdd2881aeac2546c7a6558e24779920b3e7343

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
